### ISSUE TITLE
Function pointers

### ISSUE THREAD

**Issue by shakna-israel** [shakna-israel/cnoevil#6]
One of the most complicated parts of C's syntax is declaring function pointers.

Can we simplify it?

Function pointer declarations:

```
int (*builtin_func[]) (char **) = {
  &esh_cd,
  &esh_help,
  &esh_exit
};
```

Function pointer call:

```
(*builtin_func[i])(args)
```

**Comment by ghost** [comment]
For example:

`void func(*pf)(int)`

can become:

`void func(FUNCTION(pf,int))`

with:
`
#define FUNCTION(fun,type) (*fun)(type)`

(off course you can use varidic macro paramter with ...)

```
int (*builtin_func[]) (char **) = {
  &esh_cd,
  &esh_help,
  &esh_exit
};
```
can become:

```
int (*builtin_func[]) (char **) = {
  ADDR(esh_cd),
  ADDR(esh_help),
  ADDR(esh_exit),
}
```


with:
`#define ADDR(ptr) &ptr
`

**Comment by shakna-israel** [comment]
## Deprecation Notice

This has been deprecated, and should be replaced by the largely-compatible approach [here](https://git.sr.ht/~shakna/cnoevil3/).
